### ISSUE TITLE
Does not pass all tests

### ISSUE THREAD

**Issue by louislouw** [tinohager/Nager.PublicSuffix#1]
Modified unit tests to include these tests:
https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt

This library does not current pass these tests.

**Comment by louislouw** [comment]
I have fixed the library to pass all tests. Let me know if you want to merge the code.

**Comment by tinohager** [comment]
Hi yes send me a pull request. Thanks

**Comment by louislouw** [comment]
Added pull request

**Comment by tinohager** [comment]
i have finish the merge. Thanks for your pull request

**Comment by louislouw** [comment]
I found another bug. Current implementation gives incorrect results if tree splits. Will do another pull request. Shall I do that against current branch or will you sync with master first?

**Comment by tinohager** [comment]
i have sync the branch to master

**Comment by louislouw** [comment]
Thanx. I applied my fix along with two other branches.
The last two are not fixes, but functional improvements.

**Comment by tinohager** [comment]
The last weeks i had no Internet at home, i have seen you have create a own project based on my project, and also published an own nuget package. Is one project not better then two?

**Comment by louislouw** [comment]
I was under tight deadline and needed package I could use.
Also I needed to make the parser thread safe which was a major breaking change.
If you want I can create a branch for you with those same changes?

**Comment by tinohager** [comment]
i had add also changes after your commits... if you are interested to collaborate in this project. Or you prefer your own project?
