### ISSUE TITLE
Returns null

### ISSUE THREAD

**Issue by chapeti** [tinohager/Nager.PublicSuffix#10]
Hi there! thx for your excellent work. :)

I am getting a `null` value for `domainInfo` on this situation:

`var domainParser = new DomainParser(new WebTldRuleProvider());`
`var domainInfo = domainParser.Get("s3-us-west-2.amazonaws.com");`

**Comment by tinohager** [comment]
Hi

s3-us-west-2.amazonaws.com is listet as a tld domain. If the domain a tld the result is null.

**Comment by gqqnbig** [comment]
@tinohager  Can you add XML documentation to the method so that all users know when the Get method returns null?
