### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by IvanJosipovic** [tinohager/Nager.PublicSuffix#11]
Please add support for .Net Standard.

Warning	NU1701	Package 'Nager.PublicSuffix 1.0.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by tinohager** [comment]
i have publish a new package

**Comment by IvanJosipovic** [comment]
Thank you!
