### ISSUE TITLE
How to get top private domain

### ISSUE THREAD

**Issue by tkowalczyk** [tinohager/Nager.PublicSuffix#16]
According to this article: https://github.com/google/guava/wiki/InternetDomainNameExplained, please explain me how to get Top Private Domain using this library?

**Comment by tinohager** [comment]
I don't understand your question.

**Comment by tinohager** [comment]
Is the result of your example ``.com``?

**Comment by tkowalczyk** [comment]
If I understand it well it probably should be `google.com` the public suffic is `com`

**Comment by tinohager** [comment]
var domainParser = new DomainParser(new WebTldRuleProvider());

	var domainName = domainParser.Get("mail.google.com");
	//domainName.Domain = "google";
	//domainName.Hostname = "mail.google.com";
	//domainName.RegistrableDomain = "google.com";
	//domainName.SubDomain = "mail";
	//domainName.TLD = "com";
