### ISSUE TITLE
Example Load with custom cache time not correct

### ISSUE THREAD

**Issue by mtissington** [tinohager/Nager.PublicSuffix#18]
This seems to be incorrect - there is no cacheTimeToLive on `WebTldRulProvider`

`var webTldRuleProvider = new WebTldRuleProvider(cacheTimeToLive: new TimeSpan(10, 0, 0)); //cache data for 10 hours`

**Comment by tinohager** [comment]
check the updated documentation-> FileCacheProvider

**Comment by mtissington** [comment]
thanks
