### ISSUE TITLE
Location of cached dat file

### ISSUE THREAD

**Issue by mtissington** [tinohager/Nager.PublicSuffix#20]
The cached file is downloaded to the current or active folder of the user. This can be problematic.
Can you put it in the users %Temp% folder? (`Path.GetTempPath`)

**Comment by mtissington** [comment]
We use it to get the domain name and the tld from the url but I'm not sure this is relevant.

It seems to me the user Current or Working folder is not constant so the cache file might end up in multiple places. 

The cache is by it very nature a temporary file and should be in a constant place, ie. the users temp folder.

Just my thoughts.

**Comment by tinohager** [comment]
I have add the temp path folder logic to the current code

**Comment by tinohager** [comment]
A new nuget package is available now
