### ISSUE TITLE
DomainParser.Get returns null for domains with "._"

### ISSUE THREAD

**Issue by croovy** [tinohager/Nager.PublicSuffix#22]
DomainParser.Get returns null for domains with "._". Such domains are legal:
https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

**Comment by tinohager** [comment]
For example ``_jabber._tcp.gmail.com``?

**Comment by croovy** [comment]
No, I wasn't accurate. For "a._jabber._tcp.gmail.com" it returns null and also for a.jabber._tcp.gmail.com

**Comment by tinohager** [comment]
Can you try with the ``IdnMappingNormalizer``?

``var domainParser = new DomainParser(webTldRuleProvider, new IdnMappingNormalizer());``

**Comment by croovy** [comment]
It does solve it, but I don't want to convert to unicode. I'm using your parser to parse general dns queries, so some of them indeed can't be converted to Uri as the UriNormalizer is doing.
Instead, I added to following normalizer that solves the problem in my case:
public class DnsQueryNormalizer : IDomainNormalizer
        {
            public List<string> PartlyNormalizeDomainAndExtractFullyNormalizedParts(string domain, out string partlyNormalizedDomain)
            {
                partlyNormalizedDomain = domain;
                return domain.Split('.').Reverse().ToList();
            }
        }

Thanks!
