### ISSUE TITLE
"IsValidDomain " return false

### ISSUE THREAD

**Issue by LutpyDotCom** [tinohager/Nager.PublicSuffix#25]
I'm trying to parse this URL: 

> http://sub.google.co.id/path/path2?param=&param2=

However when I call `IsValidDomain` method, it is always return false.

Did I do something wrong?

```csharp
Guard.NotNull(url, nameof(url));
if (!_domainParser.IsValidDomain(url)) 
      throw new InvalidOperationException("Invalid input url.");
```

**Comment by tinohager** [comment]
This is not a domain you have a uri. http:// is the protocol. https://en.m.wikipedia.org/wiki/Uniform_Resource_Identifier
