### ISSUE TITLE
invalid url problem

### ISSUE THREAD

**Issue by speedone** [tinohager/Nager.PublicSuffix#29]
This valid host result to null after parsing: s3-eu-west-1.amazonaws.com

**Comment by tinohager** [comment]
Amazon have set this domain on the publicsuffix list now it's the same as .com
https://publicsuffix.org/list/public_suffix_list.dat

// Amazon S3 : https://aws.amazon.com/s3/
// Submitted by Luke Wells <psl-maintainers@amazon.com>
s3.amazonaws.com
s3-ap-northeast-1.amazonaws.com
s3-ap-northeast-2.amazonaws.com
s3-ap-south-1.amazonaws.com
s3-ap-southeast-1.amazonaws.com
s3-ap-southeast-2.amazonaws.com
s3-ca-central-1.amazonaws.com
s3-eu-central-1.amazonaws.com
`s3-eu-west-1.amazonaws.com`
s3-eu-west-2.amazonaws.com
s3-eu-west-3.amazonaws.com
s3-external-1.amazonaws.com
s3-fips-us-gov-west-1.amazonaws.com
s3-sa-east-1.amazonaws.com
