### ISSUE TITLE
Fails to parse www.uberspace.de

### ISSUE THREAD

**Issue by roja** [tinohager/Nager.PublicSuffix#33]
Seems to be an issue with the following lines:

					if (parts.Count == tldRule.LabelCount)
					{
						return null;
					}

**Comment by tinohager** [comment]
// Uberspace : https://uberspace.de
// Submitted by Moritz Werner <mwerner@jonaspasche.com>
uber.space
*.uberspace.de

is a part of the publicsufflix list, and marked as TLD
