### ISSUE TITLE
Proposal: Add ctor overload to be able to receive a DomainDataStructure

### ISSUE THREAD

**Issue by fcallejon** [tinohager/Nager.PublicSuffix#35]
Hi,

In a DI environment, even using a cache, every new of `DomainParser` calls `Initialize` and that holds the creation of the parent(s) and could spike the CPU.

My proposal is: add an overload to the ctor to pass a `DomainDataStructure`.

I'm ok to make the PR.

**Comment by tinohager** [comment]
Yes send a suggestion

**Comment by fcallejon** [comment]
[Here](https://github.com/tinohager/Nager.PublicSuffix/pull/36) is the PR.
