### ISSUE TITLE
Unsure why certain domains are invalid

### ISSUE THREAD

**Issue by dmarlow** [tinohager/Nager.PublicSuffix#37]
For example: `in-berlin.de`

Must be because of the hyphen, right? Are there rules defined somewhere of how this tool works? I've come across a huge list of false negatives, unfortunately.

**Comment by tinohager** [comment]
`in-berlin.de` is listed as TLD in public suffix list

// Individual Network Berlin e.V. : https://www.in-berlin.de/
// Submitted by Christian Seitz <chris@in-berlin.de>
dyn-berlin.de
in-berlin.de
in-brb.de
in-butter.de
in-dsl.de
in-dsl.net
in-dsl.org
in-vpn.de
in-vpn.net
in-vpn.org

**Comment by dmarlow** [comment]
Hi tino, was there a fix or was this simply just closed?

**Comment by tinohager** [comment]
This is the rule list https://publicsuffix.org/list/public_suffix_list.dat
Your Domain is on the list.

**Comment by dmarlow** [comment]
If it's in the list, then why is it invalid?

**Comment by tinohager** [comment]
in-berlin.de is a TLD, `.com` or `.net` is also invalid

**Comment by tinohager** [comment]
`www.in-berlin.de` is a valid domain
